<?php
require_once 'config/Connection.php';

// Fetch dynamic carousel slides - optimized query with specific columns
$carousel_sql = "SELECT id, judul, deskripsi, gambar, btn_text, btn_link FROM Carousel ORDER BY id ASC";
$carousel_result = $conn->query($carousel_sql);
$db_slides = [];
if ($carousel_result && $carousel_result->num_rows > 0) {
    while ($row = $carousel_result->fetch_assoc()) {
        $btn_text_display = !empty($row['btn_text']) ? $row['btn_text'] : 'Profil kami';
        $btn_link_display = !empty($row['btn_link']) ? $row['btn_link'] : '#tentang';
        $db_slides[] = [
            'title' => $row['judul'],
            'subtitle' => $row['deskripsi'],
            'image' => 'uploads/' . $row['gambar'],
            'btnText' => htmlspecialchars($btn_text_display) . ' <i class="fa-solid fa-arrow-right" style="margin-left: 8px;"></i>',
            'btnLink' => htmlspecialchars($btn_link_display)
        ];
    }
}
?>
<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yayasan Kaya Tene - Bergerak Berdampak</title>
    
    <!-- DNS Prefetch & Preconnect untuk loading lebih cepat -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://cdnjs.cloudflare.com">
    
    <!-- Load fonts dengan display=swap untuk performa lebih baik -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- CSS Utama -->
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <?php require_once 'partials/Loader.php'; ?>

    <?php include 'partials/Navbar.php'; ?>

    <section class="hero" id="beranda" <?php if (empty($db_slides)) echo 'style="background-image: url(\'Public/img/hero-1.jpeg\');"'; ?>>
        <div class="hero-content-container">
            <?php if (count($db_slides) > 1): ?>
            <button class="slider-arrow prev-arrow" onclick="changeSlide(-1)"><i
                    class="fa-solid fa-chevron-left"></i></button>
            <?php endif; ?>
            
            <div class="hero-content">
                <?php if (!empty($db_slides)): ?>
                    <h1 class="hero-title" id="slide-title"><?php echo htmlspecialchars($db_slides[0]['title']); ?></h1>
                    <p class="hero-subtitle" id="slide-subtitle"><?php echo htmlspecialchars($db_slides[0]['subtitle']); ?></p>
                    <div class="hero-actions">
                        <a href="<?php echo htmlspecialchars($db_slides[0]['btnLink']); ?>" class="btn btn-primary" style="padding-left: 35px; padding-right: 35px;"
                            id="slide-link"><?php echo $db_slides[0]['btnText']; ?></a>
                    </div>
                <?php else: ?>
                    <h1 class="hero-title" id="slide-title"></h1>
                    <p class="hero-subtitle" id="slide-subtitle"></p>
                    <div class="hero-actions" style="display: none;">
                        <a href="#" class="btn btn-primary" style="padding-left: 35px; padding-right: 35px;"
                            id="slide-link"></a>
                    </div>
                <?php endif; ?>
            </div>
            
            <?php if (count($db_slides) > 1): ?>
            <button class="slider-arrow next-arrow" onclick="changeSlide(1)"><i
                    class="fa-solid fa-chevron-right"></i></button>
            <?php endif; ?>
        </div>

        <div class="slider-dots" id="slider-dots">
            <!-- Dots will be generated by JS -->
        </div>
    </section>

    <script>
        let slides = <?php echo json_encode($db_slides); ?>;
        
        if (slides.length === 0) {
            // Hide navigation arrows if there are no dynamic slides
            document.querySelectorAll('.slider-arrow').forEach(el => el.style.display = 'none');
            // Set a default background image to avoid blank hero sections
            document.getElementById('beranda').style.backgroundImage = "url('Public/img/hero-1.jpeg')";
        }

        let currentSlide = 0;
        const heroSection = document.getElementById('beranda');
        const slideTitle = document.getElementById('slide-title');
        const slideSubtitle = document.getElementById('slide-subtitle');
        const slideLink = document.getElementById('slide-link');
        const dotsContainer = document.getElementById('slider-dots');

        // Initialize dots
        if (slides.length > 0) {
            slides.forEach((_, index) => {
                const dot = document.createElement('span');
                dot.classList.add('dot');
                if (index === 0) dot.classList.add('active');
                dot.onclick = () => goToSlide(index);
                dotsContainer.appendChild(dot);
            });

            // Set the first slide content immediately
            const firstSlide = slides[0];
            heroSection.style.backgroundImage = `url('${firstSlide.image}')`;
            slideTitle.innerHTML = firstSlide.title;
            slideSubtitle.innerHTML = firstSlide.subtitle;
            slideLink.innerHTML = firstSlide.btnText;
            slideLink.href = firstSlide.btnLink;
        }

        function updateSlide() {
            if (slides.length === 0) return;
            const slide = slides[currentSlide];

            // Fade out text effect (optional enhancement)
            slideTitle.style.opacity = 0;
            slideSubtitle.style.opacity = 0;

            setTimeout(() => {
                heroSection.style.backgroundImage = `url('${slide.image}')`;
                slideTitle.innerHTML = slide.title;
                slideSubtitle.innerHTML = slide.subtitle;
                slideLink.innerHTML = slide.btnText;
                slideLink.href = slide.btnLink;

                slideTitle.style.opacity = 1;
                slideSubtitle.style.opacity = 1;
            }, 300);

            // Update dots
            document.querySelectorAll('.dot').forEach((dot, index) => {
                dot.classList.toggle('active', index === currentSlide);
            });
        }

        function changeSlide(direction) {
            currentSlide = (currentSlide + direction + slides.length) % slides.length;
            updateSlide();
        }

        function goToSlide(index) {
            currentSlide = index;
            updateSlide();
        }

        // Add smooth transition to hero text
        slideTitle.style.transition = 'opacity 0.3s ease';
        slideSubtitle.style.transition = 'opacity 0.3s ease';
        heroSection.style.transition = 'background-image 0.5s ease-in-out';

        // Auto slide
        if (slides.length > 1) {
            setInterval(() => {
                changeSlide(1);
            }, 5000);
        }
    </script>

    <section class="section" id="tentang">
        <div class="container">
            <h2 class="section-title">Sejarah <span class="text-gradient">Pendirian</span></h2>

            <div class="about-grid">
                <div class="about-image">
                    <img src="Public/img/hero-2.jpeg" alt="Masyarakat Pedesaan NTT" loading="lazy">
                </div>
                <div class="about-text glass" style="padding: 40px; border-radius: 20px;">
                    <p>
                        Provinsi Nusa Tenggara Timur (NTT) memiliki potensi alam dan budaya yang besar, namun masyarakat
                        pedesaan masih menghadapi berbagai tantangan pembangunan, termasuk kemiskinan struktural,
                        keterbatasan akses pendidikan dan kesehatan, serta rendahnya peluang ekonomi produktif.
                    </p>
                    <p>
                        Akhir tahun 2018, sekelompok anak muda diaspora Lembata di Kupang mulai membangun komunikasi
                        intensif mengenai pentingnya membentuk sebuah yayasan. Bukan sekadar lembaga formal, melainkan
                        rumah bersama gerakan sosial yang menyentuh akar rumput.
                    </p>
                    <p>
                        Yayasan Kaya Tene resmi didirikan tahun 2019 di Kupang, hadir memberikan pendekatan partisipatif
                        berbasis potensi lokal. Nama <strong>Kaya Tene</strong> dari bahasa daerah Kedang (Kabupaten
                        Lembata) yang berarti <em>"Seperti Kita"</em> atau <em>"Seperti Perahu"</em> melambangkan
                        semangat lokalitas dan empati.
                    </p>
                </div>
            </div>
        </div>
    </section>


    <section class="section" id="visi-misi" style="background-color: var(--bg-card);">
        <div class="container">
            <h2 class="section-title"><span class="text-gradient">Visi & Misi</span> Yayasan</h2>

            <div class="vm-grid">
                <div class="vm-card glass" style="border-top: 5px solid var(--primary-light);">
                    <h3>Visi</h3>
                    <p style="font-size: 1.3rem; font-weight: 500; font-style: italic;">
                        Terwujudnya masyarakat mandiri, berdaya, dan mampu mengelola potensi lokal secara berkelanjutan.
                    </p>
                </div>

                <div class="vm-card glass" style="border-top: 5px solid var(--secondary);">
                    <h3>Misi</h3>
                    <ul>
                        <li><strong class="text-gradient">Pendidikan:</strong> Meningkatkan kualitas dan karakter
                            pendidikan anak.</li>
                        <li><strong class="text-gradient">Ekonomi:</strong> Mendorong kemandirian ekonomi masyarakat
                            melalui pelatihan dan usaha mikro.</li>
                        <li><strong class="text-gradient">Lingkungan & Sosial:</strong> Menumbuhkan kesadaran akan
                            pentingnya keadilan sosial dan pelestarian lingkungan hidup.</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="section" id="berita">
        <div class="container">
            <h2 class="section-title">Berita <span class="text-gradient">Terkini</span></h2>

            <div class="news-grid">
                <?php
                // Fetch the 3 latest news from database
                $sql = "SELECT id, judul, isi, gambar, tanggal FROM Berita ORDER BY tanggal DESC LIMIT 3";
                $result = $conn->query($sql);

                if ($result && $result->num_rows > 0) {
                    while ($row = $result->fetch_assoc()) {
                        // Extract excerpt (first 100 characters)
                        $excerpt = strlen($row['isi']) > 150 ? substr($row['isi'], 0, 150) . '...' : $row['isi'];
                        // For placeholder image if no image found:
                        $gambar = $row['gambar'] ? 'uploads/' . htmlspecialchars($row['gambar']) : 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80';
                        $tanggal = date('d F Y', strtotime($row['tanggal']));

                        echo '
                        <div class="news-card glass">
                            <img src="' . $gambar . '" alt="Berita" class="news-img" loading="lazy" onerror="this.src=\'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80\'">
                            <div class="news-content">
                                <div class="news-date">' . $tanggal . '</div>
                                <h4 class="news-title">' . htmlspecialchars($row['judul']) . '</h4>
                                <p class="news-excerpt">' . htmlspecialchars($excerpt) . '</p>
                                <a href="views/detail-berita.php?id=' . $row['id'] . '" class="news-link">Baca Selengkapnya <i class="fa-solid fa-arrow-right"></i></a>
                            </div>
                        </div>';
                    }
                } else {
                    echo '
                    <div class="glass" style="grid-column: 1/-1; padding: 40px; text-align: center; border-radius: 20px;">
                        <h3 class="text-muted">Belum ada berita yang diterbitkan.</h3>
                        <p>Silakan kunjungi kembali nanti.</p>
                    </div>';
                }
                ?>
            </div>

            <div style="text-align: center; margin-top: 50px;">
                <a href="views/berita.php" class="btn btn-primary" style="padding: 12px 40px;">Lihat Semua Berita</a>
            </div>
        </div>
    </section>

    <?php include 'views/galeri.php'; ?>

    <section class="section" id="kontak">
        <div class="container">
            <h2 class="section-title">Hubungi <span class="text-gradient">Kami</span></h2>
            <p class="section-subtitle-center">
                Mari berkolaborasi dan wujudkan perubahan bersama Yayasan Kaya Tene. Jangan ragu untuk menghubungi kami melalui media di bawah ini.
            </p>

            <div class="contact-grid">
                <!-- WhatsApp -->
                <a href="https://wa.me/6282341067389?text=Halo%20Admin%20Yayasan%20Kaya%20Tene%2C%20saya%20tertarik%20dan%20ingin%20bertanya%20lebih%20lanjut%20mengenai%20program%20yayasan."
                    target="_blank" class="contact-card">
                    <div class="contact-icon wa">
                        <i class="fa-brands fa-whatsapp"></i>
                    </div>
                    <h3>WhatsApp</h3>
                    <p>Chat langsung dengan admin kami untuk informasi lebih lanjut.</p>
                </a>

                <!-- Instagram -->
                <a href="https://www.instagram.com/kaya_tene?igsh=MWJlYm15MXBhbzFzdA==" target="_blank" class="contact-card">
                    <div class="contact-icon ig">
                        <i class="fa-brands fa-instagram"></i>
                    </div>
                    <h3>Instagram</h3>
                    <p>Ikuti kegiatan harian dan kabar terbaru kami di Instagram.</p>
                </a>

                <!-- Email -->
                <a href="https://mail.google.com/mail/?view=cm&fs=1&to=yayasankayatene@gmail.com&su=Tanya%20Sistem%20Yayasan%20Kaya%20Tene&body=Halo%20Admin%20Kaya%20Tene,%0A%0ASaya%20ingin%20bertanya:"
                    target="_blank" class="contact-card">
                    <div class="contact-icon mail">
                        <i class="fa-regular fa-envelope"></i>
                    </div>
                    <h3>Email</h3>
                    <p>Kirimkan tawaran kerjasama atau pertanyaan umum melalui email.</p>
                </a>
            </div>
        </div>
    </section>
    <?php include 'views/Messages.php'; ?>

    <?php include 'partials/Footer.php'; ?>

</body>


</html>
<?php
// Flush output buffer untuk kirim konten ke browser lebih cepat
if (ob_get_level() > 0) {
    ob_end_flush();
}
?>