<?php
require_once 'config/Connection.php';
?>
<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yayasan Kaya Tene - Seperti Kita, Seperti Perahu</title>
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <?php require_once 'partials/Loader.php'; ?>

    <?php include 'partials/Navbar.php'; ?>

    <section class="hero" id="beranda">
        <div class="hero-content-container">
            <button class="slider-arrow prev-arrow" onclick="changeSlide(-1)"><i
                    class="fa-solid fa-chevron-left"></i></button>
            <div class="hero-content">
                <h1 class="hero-title" id="slide-title">Selamat datang</h1>
                <p class="hero-subtitle" id="slide-subtitle">Yayasan Kaya Tene - Seperti Kita, Seperti Perahu</p>
                <div class="hero-actions">
                    <a href="#tentang" class="btn btn-primary" style="padding-left: 35px; padding-right: 35px;"
                        id="slide-link">Profil
                        kami <i class="fa-solid fa-arrow-right" style="margin-left: 8px;"></i></a>
                </div>
            </div>
            <button class="slider-arrow next-arrow" onclick="changeSlide(1)"><i
                    class="fa-solid fa-chevron-right"></i></button>
        </div>

        <div class="slider-dots" id="slider-dots">
            <!-- Dots will be generated by JS -->
        </div>
    </section>

    <script>
        const slides = [
            {
                title: "Selamat datang",
                subtitle: "Yayasan Kaya Tene - Seperti Kita, Seperti Perahu",
                image: "Public/img/hero-1.jpeg",
                btnText: 'Profil kami <i class="fa-solid fa-arrow-right" style="margin-left: 8px;"></i>',
                btnLink: "#tentang"
            },
            {
                title: "Kemandirian Masyarakat",
                subtitle: "Mendorong perekonomian lokal melalui pemberdayaan",
                image: "Public/img/hero-2.jpeg",
                btnText: 'Visi & Misi <i class="fa-solid fa-arrow-right" style="margin-left: 8px;"></i>',
                btnLink: "#visi-misi"
            },
            {
                title: "Pendidikan Anak",
                subtitle: "Meningkatkan kualitas dan karakter generasi penerus",
                image: "Public/img/hero-3.jpeg",
                btnText: 'Berita Terkini <i class="fa-solid fa-arrow-right" style="margin-left: 8px;"></i>',
                btnLink: "#berita"
            }
        ];

        let currentSlide = 0;
        const heroSection = document.getElementById('beranda');
        const slideTitle = document.getElementById('slide-title');
        const slideSubtitle = document.getElementById('slide-subtitle');
        const slideLink = document.getElementById('slide-link');
        const dotsContainer = document.getElementById('slider-dots');

        // Initialize dots
        slides.forEach((_, index) => {
            const dot = document.createElement('span');
            dot.classList.add('dot');
            if (index === 0) dot.classList.add('active');
            dot.onclick = () => goToSlide(index);
            dotsContainer.appendChild(dot);
        });

        function updateSlide() {
            const slide = slides[currentSlide];

            // Fade out text effect (optional enhancement)
            slideTitle.style.opacity = 0;
            slideSubtitle.style.opacity = 0;

            setTimeout(() => {
                heroSection.style.backgroundImage = `url('${slide.image}')`;
                slideTitle.innerHTML = slide.title;
                slideSubtitle.innerHTML = slide.subtitle;
                slideLink.innerHTML = slide.btnText;
                slideLink.href = slide.btnLink;

                slideTitle.style.opacity = 1;
                slideSubtitle.style.opacity = 1;
            }, 300);

            // Update dots
            document.querySelectorAll('.dot').forEach((dot, index) => {
                dot.classList.toggle('active', index === currentSlide);
            });
        }

        function changeSlide(direction) {
            currentSlide = (currentSlide + direction + slides.length) % slides.length;
            updateSlide();
        }

        function goToSlide(index) {
            currentSlide = index;
            updateSlide();
        }

        // Add smooth transition to hero text
        slideTitle.style.transition = 'opacity 0.3s ease';
        slideSubtitle.style.transition = 'opacity 0.3s ease';
        heroSection.style.transition = 'background-image 0.5s ease-in-out';

        // Auto slide
        setInterval(() => {
            changeSlide(1);
        }, 5000);
    </script>

    <section class="section" id="tentang">
        <div class="container">
            <h2 class="section-title">Sejarah <span class="text-gradient">Pendirian</span></h2>

            <div class="about-grid">
                <div class="about-image">
                    <img src="Public/img/hero-2.jpeg" alt="Masyarakat Pedesaan NTT">
                </div>
                <div class="about-text glass" style="padding: 40px; border-radius: 20px;">
                    <p>
                        Provinsi Nusa Tenggara Timur (NTT) memiliki potensi alam dan budaya yang besar, namun masyarakat
                        pedesaan masih menghadapi berbagai tantangan pembangunan, termasuk kemiskinan struktural,
                        keterbatasan akses pendidikan dan kesehatan, serta rendahnya peluang ekonomi produktif.
                    </p>
                    <p>
                        Akhir tahun 2018, sekelompok anak muda diaspora Lembata di Kupang mulai membangun komunikasi
                        intensif mengenai pentingnya membentuk sebuah yayasan. Bukan sekadar lembaga formal, melainkan
                        rumah bersama gerakan sosial yang menyentuh akar rumput.
                    </p>
                    <p>
                        Yayasan Kaya Tene resmi didirikan tahun 2019 di Kupang, hadir memberikan pendekatan partisipatif
                        berbasis potensi lokal. Nama <strong>Kaya Tene</strong> dari bahasa daerah Kedang (Kabupaten
                        Lembata) yang berarti <em>"Seperti Kita"</em> atau <em>"Seperti Perahu"</em> melambangkan
                        semangat lokalitas dan empati.
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section class="section" id="visi-misi" style="background-color: var(--bg-card);">
        <div class="container">
            <h2 class="section-title"><span class="text-gradient">Visi & Misi</span> Yayasan</h2>

            <div class="vm-grid">
                <div class="vm-card glass" style="border-top: 5px solid var(--primary-light);">
                    <h3>Visi</h3>
                    <p style="font-size: 1.3rem; font-weight: 500; font-style: italic;">
                        Terwujudnya masyarakat mandiri, berdaya, dan mampu mengelola potensi lokal secara berkelanjutan.
                    </p>
                </div>

                <div class="vm-card glass" style="border-top: 5px solid var(--secondary);">
                    <h3>Misi</h3>
                    <ul>
                        <li><strong class="text-gradient">Pendidikan:</strong> Meningkatkan kualitas dan karakter
                            pendidikan anak.</li>
                        <li><strong class="text-gradient">Ekonomi:</strong> Mendorong kemandirian ekonomi masyarakat
                            melalui pelatihan dan usaha mikro.</li>
                        <li><strong class="text-gradient">Lingkungan & Sosial:</strong> Menumbuhkan kesadaran akan
                            pentingnya keadilan sosial dan pelestarian lingkungan hidup.</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="section" id="berita">
        <div class="container">
            <h2 class="section-title">Berita <span class="text-gradient">Terkini</span></h2>

            <div class="news-grid">
                <?php
                // Fetch the 3 latest news from database
                $sql = "SELECT id, judul, isi, gambar, tanggal FROM Berita ORDER BY tanggal DESC LIMIT 3";
                $result = $conn->query($sql);

                if ($result && $result->num_rows > 0) {
                    while ($row = $result->fetch_assoc()) {
                        // Extract excerpt (first 100 characters)
                        $excerpt = strlen($row['isi']) > 150 ? substr($row['isi'], 0, 150) . '...' : $row['isi'];
                        // For placeholder image if no image found:
                        $gambar = $row['gambar'] ? 'uploads/' . htmlspecialchars($row['gambar']) : 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80';
                        $tanggal = date('d F Y', strtotime($row['tanggal']));

                        echo '
                        <div class="news-card glass">
                            <img src="' . $gambar . '" alt="Berita" class="news-img" onerror="this.src=\'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80\'">
                            <div class="news-content">
                                <div class="news-date">' . $tanggal . '</div>
                                <h4 class="news-title">' . htmlspecialchars($row['judul']) . '</h4>
                                <p class="news-excerpt">' . htmlspecialchars($excerpt) . '</p>
                                <a href="views/detail-berita.php?id=' . $row['id'] . '" class="news-link">Baca Selengkapnya <i class="fa-solid fa-arrow-right"></i></a>
                            </div>
                        </div>';
                    }
                } else {
                    echo '
                    <div class="glass" style="grid-column: 1/-1; padding: 40px; text-align: center; border-radius: 20px;">
                        <h3 class="text-muted">Belum ada berita yang diterbitkan.</h3>
                        <p>Silakan kunjungi kembali nanti.</p>
                    </div>';
                }
                ?>
            </div>

            <div style="text-align: center; margin-top: 50px;">
                <a href="views/berita.php" class="btn btn-primary" style="padding: 12px 40px;">Lihat Semua Berita</a>
            </div>
        </div>
    </section>

    <?php include 'views/galeri.php'; ?>

    <?php include 'partials/Footer.php'; ?>

</body>


</html>