CREATE DATABASE kaya_tene;
ALTER DATABASE kaya_tene CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE Berita(
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    isi TEXT NOT NULL,
    gambar VARCHAR(255) NOT NULL,
    tanggal DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Admin(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    tanggal DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Galeri (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    gambar VARCHAR(255) NOT NULL,
    tanggal DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
